config/routes.rb
Kirpeep::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'auth/:provider/callback', :to => 'sessions#facebook_create'
  match 'auth/failure', to: redirect('/')
  match '/sessions/signin', :to => 'sessions#signin'

  match  'destroy_session',      :to => 'sessions#destroy'
  match  '/create_listing/',     :to => 'userlistings#create'
  match  '/new_listing',         :to => 'userlistings#new'
  match  '/exchange_listing/',   :to => 'userlistings#show_listing_exchange'
  match  '/show_listing/',       :to => 'userlistings#show_listing_result'
  match  '/destroy_listing',     :to => 'userlistings#destroy'
  match  '/share/:id',           :to => 'userlistings#share'
  match  '/profile/:id',         :to => 'users#profile'
  match  '/user_exchanges/:id',  :to => 'users#exchanges'
  match  '/messages/:id',        :to => 'users#messages'
  match  '/view/:id',            :to => 'users#view'
  match  '/users/:id/chat_status/:status', :to => 'users#chat_status'
  get  '/signup/',             :to => 'users#new'
  post   '/signup/',             :to => 'users#create'
  match  '/signup/:email&:pass', :to => 'users#new'
  match  '/users/:id/offers',    :to => 'users#offers'
  match  '/users/:id/needs/',    :to => 'users#needs'
  match  '/users/:id/need/:listing', :to => 'users#get_need'
  match  '/users/:id/offer/:listing', :to => 'users#get_offer'
  match '/users/:id/transactions', :to => 'transaction#show'
  match  '/search/',           :to => 'search#search'
  match  '/initiate_exchange/', :to => 'exchanges#initiate_exchange'
  match  '/create_exchange/', :to => 'exchanges#create'
  match  '/destroy_exchange/',  :to => 'exchanges#destroy'
  match  '/accept_exchange/', :to => 'exchanges#accept_exchange', :as => 'accept_exchange'
  match  '/accept_perform/' , :to => 'exchanges#accept_perform' , :as => 'accept_perform'
  match  '/rate_exchange/'  , :to => 'exchanges#rate_exchange' , :as => 'rate_exchange'
  match  '/add_offer/',   :to => 'exchanges#add_offer'
  match  '/add_need/',   :to => 'exchanges#add_need'
  match  '/exch_add_kirpoints/',    :to => 'exchanges#add_kirpoints_listing'
  match  '/sendmessage/', :to => 'messages#new'
  match  '/mark_unread/', :to => 'messages#markAsUnread'
  match  '/mark_read/', :to => 'messages#markAsRead'
  put '/userlisting/:id', :to => 'userlistings#update'
  get  '/edit_listing/',  :to => 'userlistings#edit'
  match  '/get_listing/', :to => 'userlistings#getListing'
  get '/userlisting/random', :to => 'userlistings#random'
  get '/userlisting/:id/ditto/', :to => 'userlistings#ditto'
  get '/userlisting/:id/edit_location/', :to => 'userlistings#edit_location'
  get  '/sendmessage/?id=:id&replyTo=:reply_message_id'    , :to => 'messages#new'
  match '/add_review/', :to => 'reviews#new'
  get '/forgot/', :to => 'users#forgot'
  post '/forgot', :to => 'users#process_forgot'
  get '/resetpassword/', :to => 'users#reset_password'
  post '/resetpassword/', :to => 'users#process_reset_password'
  get '/activate/', :to => 'users#activate'

  get '/kirpoints', :to => 'users#kirpoints'
  post '/kirpoints', :to => 'users#add_kirpoints'
  match '/kirpoints/confirm', :to=> 'users#confirm'
  match '/kirpoints/complete', :to=> 'users#complete'
  get '/kirpoints/cashout', :to=>'users#cashout_kirpoints'
  post '/kirpoints/cashout', :to=>'users#process_cashout_kirpoints'
  match 'kirpoints/gift', :to => 'users#gift_kirpoints'

  post '/sms/verify', :to => 'sms#verify'
  post '/sms/recieve', :to => 'sms#recieve'
  get '/listing/:id', :to => 'userlistings#show_listing'
  get '/listing/:id/report', :to => 'userlistings#report'

  match '/tos', :to => 'application#tos'
  match '/privacy', :to => 'application#privacy'
  match '/how', :to => 'application#how'
  match '/about', :to => 'application#about'
  match '/faq', :to => 'application#faq'
  post '/admin/credit', :to => 'admin#credit'
  
  post '/listingsmash/:id_y/over/:id_n/in/:time', :to => 'listing_smash#add_listing_smash_result'
  get  '/listingsmash/newlistings', :to => 'listing_smash#render_new_listings'
  get '/listingsmash/:lid1/vs/:lid2', :to => 'listing_smash#percentVs'
  get  '/listingsmash', :to => 'listing_smash#show'

  root :to => 'sessions#index'
  resources :search
  resources :users do |user|
  end
  resources :userlistings
  resources :sessions#, :only => [:new, :create, :destroy]
  resources :exchanges
  resources :profiles
  resources :messages
  resources :transaction
  resources :admin
  resources :sms, :only => [:verify, :recieve]
  resources :chat do |chat|
    post "reply", :to => "chat#reply"
  end

end

app/models/exchange.rb
#################################################
# Model::Exchagne								#
# Desc: Base class for all other exchanges		#
# Comments:, 									#
#################################################

class Exchange < ActiveRecord::Base
  attr_accessible :exchange_items_attributes, :message_attributes, :reviews_attributes, :initUser, :targUser, :init_list_id, :targ_list_id, :type
  has_many :exchange_items, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_one :message, :dependent => :destroy 
  accepts_nested_attributes_for :exchange_items
  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :message
end

app/controllers/exchanges_controller.rb
####################################################
# Controller::ExchangesControler                   #
# Desc:                                            #
# Comments:                                        #
####################################################

class ExchangesController < ApplicationController

  def create
    @user = current_user
    @exchange = InitiateExchange.new params[:initiate_exchange]
    @exchange.initAcpt = true
    
    if @exchange.save
      flash[:notice] = 'exchange saved.'
      @targUser = User.find(@exchange.targUser)
      @initUser = User.find(@exchange.initUser)
      UserMailer.message_email(@targUser, @initUser, @initUser.name + " would like to start an exchange with you.", "Go to your profile on kirpeep.com to see your new exchange!" ).deliver
      
      @initItems = exchanged_items(@exchange.id).find_all_by_init_user_id(@user.id)

      for item in @initItems
        if item.kirpoints_amounts != nil
          commitKirpoints(@user, item.kirpoints_amounts)
        end
      end
      redirect_to current_user
    else
  	  flash[:error] = @exchange.errors.full_messages.to_sentence
      redirect_to current_user
    end
  end

  def show
    @exch = Exchange.find(params[:id]) 
    @targUser = User.find(@exch.targUser )
    @initUser = User.find(@exch.initUser )

    if current_user.id != @targUser.id && current_user.id != @initUser.id
      redirect_to "/users/"+current_user.id.to_s
    end
    @exchange_items = exchanged_items(@exch.id)
    #not the greatest way to do this, with this code we will not be able to do \
    #multiparty exchanges. To resolve a migration should be made to include initUsers id 
    #so that it doesn't need to be pulled from the listing
    #for now the items with :targ_user_id will be assinged
    #11/11/12 - I added the migration and now items have init and targ ids
    @targItems = @exchange_items.find_all_by_targ_user_id( @targUser.id)
    @initItems = @exchange_items.find_all_by_targ_user_id(@initUser.id)
  end

  def new
    @exchange = InitiateExchange.new
  end
  
  def destroy
    exch = Exchange.find(params[:id])
    #change value of 'is_deleted' to true so that it no longer displays
    exch.is_deleted = true

    if exch.save
      flash[:notice] = 'Exchange Removed'  
      
      respond_to do |format|
        format.html {redirect_to current_user}
        format.js 
      end
    else

      flash[:error] = exch.errors

        if exch.errors.any?
            exch.errors.full_messages.each do |msg|
                puts msg
            end
        end

      redirect_to current_user
    end
  end

  def initiate_exchange
    @initexch = InitiateExchange.new
    @user = current_user
    @targListing = UserListing.find params[:id]
    @targUser = @targListing.user
    
    render 'initiate_exchange'
  end

  #Acceptance of initiated Exchange
  def accept_exchange
    exch = InitiateExchange.find(params[:exch_id])
    @initUser = User.find exch.initUser
    @targUser = User.find exch.targUser

    if(exch.initUser == params[:user_id])
      exch.initAcpt = true

      @initItems = exchanged_items(exch.id).find_all_by_init_user_id(params[:user_id])
      for item in @initItems
        if item.kirpoints_amounts != nil
          commitKirpoints(@initUser, item.kirpoints_amounts)
        end
      end
      UserMailer.message_email(@targUser, @initUser, @initUser.name + " would like to start an exchange with you.", "Go to your profile on kirpeep.com to see your new exchange!" ).deliver
    else 
      exch.targAcpt = true
      @targItems = exchanged_items(exch.id).find_all_by_init_user_id(params[:user_id])
      for item in @targItems
        if item.kirpoints_amounts != nil
          commitKirpoints(@targUser, item.kirpoints_amounts)
        end
      end
      UserMailer.message_email(@initUser, @targUser, @targUser.name + " has accepted the exchange.", "Go to your profile on kirpeep.com and accept the exchange." ).deliver
    end

    if(exch.initAcpt == true && exch.targAcpt == true)
    
      
      exch.type = 'PerformExchange'
      exch.save

      exch = exch.becomes(PerformExchange)

      #create codes and save
      initConfCode = 'c-' + User.generateToken()[0..5]
      targConfCode = 'c-' + User.generateToken()[0..5]
      exch.initConfCode = initConfCode.downcase
      exch.targConfCode = targConfCode.downcase

      if exch.save
        # send SMS Messages Here
        @targUser = User.find(exch.targUser)
        @initUser = User.find(exch.initUser)
        
        UserMailer.message_email(@targUser, @initUser, @initUser.name + " is ready to perform the exchange.", "Go to your profile on kirpeep.com to see accept the exchange or use our SMS confirmation during your meet up to confirm the trade. Your code is " + targConfCode ).deliver
        UserMailer.message_email(@initUser, @targUser, @targUser.name + " is ready to perform the exchange.", "Go to your profile on kirpeep.com to see accept the exchange or use our SMS confirmation during your meet up to confirm the trade.  Your code is " + initConfCode  ).deliver

        # only send if we have verified phone numbers for both parties. 
        if (@targUser.profile.phone_number && @targUser.profile.number_verified == true) &&
            (@initUser.profile.phone_number && @initUser.profile.number_verified == true)

           #Then send SMS conf codes
           sendTxt(@targUser.profile.phone_number, "Your code is #{exch.targConfCode}. Text the other person's code when your are finished exchanging to let us know it's complete. -Kirpeep")
           sendTxt(@initUser.profile.phone_number, "Your code is #{exch.initConfCode}. Text the other person's code when your are finished exchanging to let us know it's complete. -Kirpeep")
        end

        flash[:notice] = 'exchange moved to '  + (exch.type).to_s
        redirect_to current_user
        return
      else
        flash[:notice] = 'did not save'
        redirect_to current_user
        return
      end
    end

    flash[:notice] = 'exchange updated.'
    redirect_to current_user
  end

  #Acceptance of Performed Exchange
  def accept_perform
    exch = PerformExchange.find(params[:exch_id])
    
    @targUser = User.find(exch.targUser)
    @initUser = User.find(exch.initUser)
        
    if(exch.initUser == params[:user_id])
      UserMailer.message_email(@targUser, @initUser, @initUser.name + " is ready to be rated.", "Go to your profile on kirpeep.com to rate your exchange." ).deliver
      exch.initComp = true
      flash[:notice] = 'exchange updated.'
    else
      UserMailer.message_email(@initUser, @targUser, @targUser.name + " is ready to be rated.", "Go to your profile on kirpeep.com to rate your exchange." ).deliver  
      exch.targComp = true
      flash[:notice] = 'exchange updated.'
    end
      exch.save
    if(exch.initComp == true && exch.targComp == true)
      exch.type = 'RateExchange'
      exch.save 

      exch = exch.becomes(RateExchange)
      if exch.save
        flash[:notice] = 'exchange moved to '  + (exch.type)
      
        @initItems = exchanged_items(exch.id).find_all_by_init_user_id(@initUser.id)
        for item in @initItems
          if item.kirpoints_amounts != nil
            transferKirpoints(@initUser, @targUser, item.kirpoints_amounts)
          end
        end
      
        @targItems = exchanged_items(exch.id).find_all_by_init_user_id(@targUser.id)
        for item in @targItems
          if item.kirpoints_amounts != nil
            transferKirpoints(@targUser, @initUser, item.kirpoints_amounts)
          end
        end
        redirect_to current_user
        return
      else
          flash[:notice] = 'did not save'
          redirect_to current_user
          return
      end
    end
    flash[:notice] = 'exchange updated.'
    redirect_to current_user
  end

  def rate_exchange
    exch = RateExchange.find(params[:exch_id])

    if(exch.initUser == params[:user_id])
      exch.init_rating_time    = params[:time]
      exch.init_rating_cost    = params[:cost]
      exch.init_rating_ease    = params[:ease]
      exch.init_rating_overall = params[:overall]
      exch.init_comments       = params[:comments]
    else
      exch.targ_rating_time    = params[:time]
      exch.targ_rating_cost    = params[:cost]
      exch.targ_rating_ease    = params[:ease]
      exch.targ_rating_overall = params[:overall]
      exch.targ_comments       = params[:comments]
    end
    exch.save
    if(exch.init_rating_overall != nil && exch.targ_rating_overall != nil)
      ex_type = exch.type
      exch.type = 'ArchivedExchange'
      exch.save 

      exch = exch.becomes(ArchivedExchange)
      exch.type_when_term = ex_type
      if exch.save
          flash[:notice] = 'exchange moved to ' + (exch.type).to_s
          redirect_to current_user
          return
      else
          flash[:notice] = 'did not save'
          redirect_to current_user
          return
      end
    end
    flash[:notice] = 'Rated exchange '
    redirect_to current_user
  end

  def exchanged_items
    ExchangeItem.where("exchange_id = ?", params[:id])
  end

  def exchanged_items(id)
    ExchangeItem.where("exchange_id = ?", id)
  end

  def add_need
    initUser = User.find(params[:init])
    targUser = User.find(params[:targ])

    userNeeds = initUser.needs.all.map { |need| [need.title, need.id] }
    targOffers = targUser.offers.all.map { |offer| [offer.title, offer.id] } 
    dropdownItems = [["Select an item", -9],[":Your Needs:", -9] ]  
    dropdownItems.concat(userNeeds)
    dropdownItems = dropdownItems + [[":Their Offers:", -9]]
    dropdownItems.concat(targOffers)

    render :partial => 'create_need', :locals => {:initUser => initUser, :targUser => targUser, :dropdownItems => dropdownItems}    
  end

  def add_offer
    initUser = User.find(params[:init])
    targUser = User.find(params[:targ])

    userOffers = initUser.offers.all.map { |offer| [offer.title, offer.id] }

app/views/exchanges/_create_kirpoints.html.erb
<script type="text/javascript">
    initContext = <%= initUser.to_json.html_safe %>;
    $(document).ready(function() {
        $('#add-kirpoints').live('click', function(e) {
            e.preventDefault();
            if($(this).prev('.amount').val() > initContext['kirpoints']){
                alert("You Do Not Have Sufficent Funds. Add some kirpoints");
                return false;
            }
            else{
                $(this).prev('.amount').before('<span>'+$(this).prev('.amount').val()+' Kirpoints</span>');
                if(console) console.log($(this).closest('.amount'));
                $('.points').val($(this).prev('.amount').val());
                $('.points').removeClass('points');

                $(this).prev('.amount').remove();
                $(this).hide();
            }
        });
    });
</script>

<div class="rounded-map shadow">
    <a type="button" class="close" aria-hidden="true">×</a>
    <div>
        <span>Throw in some Kirpoints:</span>
    </div>
    <div>
        <%= text_field_tag "amount", '$$$', :class => 'amount' %>
        <%= submit_tag "Add", :id => "add-kirpoints" %>
        <%= fields_for 'initiate_exchange[exchange_items_attributes][]', Time.now.to_i  do |fa| %>
            <%=fa.hidden_field :user_listing_id, :value => listingType %>
            <%=fa.hidden_field :targ_user_id, :value => targUser.id %>
            <%=fa.hidden_field :init_user_id, :value => initUser.id %>
            <%=fa.hidden_field :kirpoints_amounts, :value => -8, :class => "points" %>
        <% end %>
    </div>
</div>

app/views/exchanges/_create_need.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$('#listing_id option[value = -9]').each(function(){
			$(this).attr('disabled', 'disabled');
		});
	});
</script>

<div class="rounded-need shadow">
	<a type="button" class="close" aria-hidden="true">×</a>
    <div>
        <span id="selectNeed">Select a Need or <a href="/new_listing?type=need" class="dynamolink">Create</a> a new one.
        </span>
    </div>
    <div>
            <%= select_tag :listing_id, options_for_select(dropdownItems), { :class => 'selectNeedListing span'} %>
    </div>
</div>

app/views/exchanges/_create_offer.html.erb
<script type="text/javascript">
    $(document).ready(function() {
        $('#listing_id option[value = -9]').each(function(){
            $(this).attr('disabled', 'disabled');
        });
    });
</script>
<div class="rounded-offer shadow">
	<a type="button" class="close" aria-hidden="true">×</a>
    <div>
        <span id="selectoffer">Select a offer or <a href="/new_listing?type=offer" class="dynamolink">Create</a> a new one.
        </span>
    </div>
    <div>
    	<span>
            <%= select_tag :listing_id, options_for_select(dropdownItems), { :class => 'selectOfferListing span'} %>
    	</span>
        
    </div>
</div>

app/views/exchanges/_initiate_exchange_form.html.erb
<%= form_for(@initexch, :url => create_exchange_path) do |f| %>
    
    <%= f.hidden_field :targUser, :value => @targListing.user.id %>
    <%= f.hidden_field :initUser, :value => current_user.id %>

    
    <div class="row">
        <div class="span6">
            <h3 id="myModalLabel">Initiate Exchange</h3>
            <div class='align-center' id="exchangeStatus">
                <div class="progress progress-striped">
                    <div class="bar" style="width: 20%;"></div>
                </div>
            </div>
        </div>
    </div>
    
    <%= render 'exchange_header' %>
    
    <div class='row'>
    <!--left side-->
        <div class='span6'>
            <div><span id="getting">You are getting...</span></div>

            <!--User needs / Targ Offers -->
            <div class="tabbable tabs-left">
                <ul class="nav nav-tabs" id="userItems">
                    <li class="active"><a href="#offer" data-toggle="tab">Listing 1</a></li>
                    <li id="user_new_link"><%= link_to '+', '#'%></li>
                </ul>
                <div class="tab-content" id="userExchItems">
                    <div class="tab-pane active" id="offer">
                        <!--  Listing -->
                        <% if @targListing.listingType == "offer" %>
                        <div data-url="/get_listing?id=<%= @targListing.id %>&targ=<%= current_user.id %>&init=<%= @targUser.id %>&type=offer" id="targlisting" class="span4"></div>
                        <% else %>
                        <div data-url="/add_need?init=<%= current_user.id %>&targ=<%= @targUser.id %>" id="targlisting" class="span4"></div>
                        <%end%>
                        <!-- End of Offer Listing --> 
                    </div>
                </div>
            </div>
            
        </div>
        
        <!--Right Side-->
        <div class='span6'>
            <div><span id="giving">You are giving this...</span></div>

            <!-- Needs-->
            <div class="tabbable tabs-right">
                <ul class="nav nav-tabs" id="targItems">
                    <li class="active"><a href="#needs" data-toggle="tab">Listing 1</a></li>
                    <li id="targ_new_link">
                        <%= link_to '+', '#' %>
                    </li>
                </ul>
                <div class="tab-content" id="targExchItems">
                    <div class="tab-pane active" id="needs">
                        <!-- Need Listing -->
                        <% if @targListing.listingType == "offer" %>
                        <div data-url="/add_offer?init=<%= @user.id %>&targ=<%= @targUser.id %>" id="initlisting" class="span4"></div>
                        <%else%>
                            <div data-url="/get_listing?id=<%= @targListing.id %>&targ=<%= @targUser.id %>&init=<%= current_user.id %>&type=need" id="initlisting" class="span4"></div>
                        <%end%>
                        <!--End of Need Listing-->
                    </div>
                </div>
            </div>
            
        </div>
        <div class='clearfix'></div>
            
        <!--Opens Bottom Section-->
        <div class="row" id="messagebox">
            <div class='span6 offset3'>
                <%= fields_for 'initiate_exchange[message_attributes]' do |message| %>
                <span>Message</span>
                    <%= message.text_area :text, :class => 'rounded-map', :rows => '4', :style => "width:95%" %>
                    <%= message.hidden_field :targUser, :value => @targListing.user.id %>
                    <%= message.hidden_field :initUser, :value => current_user.id %>
                    <%= message.hidden_field :responseToMsgID, :value => 'exchange' %>
                <%end%>
            </div>
        </div>
    </div>
    <div class="span6 offset3">
        <%= f.submit 'Initiate Exchange', :class => "btn btn-primary" %> 
    </div>
<% end %>

app/views/exchanges/_initiated_exchange.html.erb
<html>
<head>
    <%= stylesheet_link_tag    "results.css" %>
    <script type="text/javascript">
    $(document).ready(function() {
        $(".itemTemplate").each(function(){
            $(this).insertERBTemplateAjax();
        });
    });
    </script>
</head>
<body>
    <div class="container">
        <%= render 'shared/header' %>
        <!-- start -->
        <div class="row">
            <div class="span6">
                <h3 id="myModalLabel">Initiated Exchange</h3>
                <div class='align-center' id="exchangeStatus">
                    <div class="progress progress-striped">
                        <div class="bar" style="width: 25%;"></div>
                    </div>
                </div>
            </div>
        </div>
        
        <%= render 'exchange_header' %>
        <%= render 'exchange_items' %>
        <!-- Exchange Message-->
        <div class="row" id="messagebox">
            <div class='span6 offset3'>    
                <span>Message</span>
                <div class="rounded-map shadow" id="message" style="overflow:scroll; height: 100px;">
                    <% current_message = @exch.message%>
                    <% reply_message_id = current_message.id %>
                    <% begin %>
                        <%= render :partial =>current_message, :locals => {:current_message => current_message} %>
                        <% reply_message_id = current_message.id %>
                        <% current_message = Message.where(:responseToMsgID => current_message.id).first %>
                    <% end while(current_message != nil) %>
                    <div>
                        <%= form_for Message.new, :remote => true, :html => {:class => "reply_message"} do |f| %>
             
                            <%= f.hidden_field :initUser, :value => current_user.id %>
                            <%= f.hidden_field :responseToMsgID, :value =>  reply_message_id %>
                            <% if is_current_user(@initUser) %>
                                <%= f.hidden_field :targUser, :value => @targUser.id %>
                            <% else %>
                                <%= f.hidden_field :targUser, :value => @initUser.id %>
                            <% end %>
                            <%= f.text_field :text %>
                            
                            <%= f.submit :reply, :class => "btn btn-primary" %>
                        <% end %>
                    </div>
                </div>
            </div><!-- .row-fluid-->
            <div id="submitButton">
            <% if((@exch.initUser).to_s == (current_user.id).to_s ) %>
                <% if @exch.initAcpt %>
                    <span>Waiting for user</span>
                <%else%>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <%= f.submit "Sign In", {:class => "btn btn-primary"} %>
                <!--<%= button_to "Accept", accept_exchange_path(:exch_id => @exch.id, :user_id => @exch.initUser) %>-->
                <%end%>
            <%else%>
                <% if @exch.targAcpt %>
                    <span>Waiting for user</span>
                <%else%>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <%= button_to "Accept", accept_exchange_path(:exch_id => @exch.id, :user_id => @exch.targUser), {:class => "btn btn-primary"} %>
                <%end%>
            <%end%>    
            </div>
        </div>
        <%= render 'shared/footer' %>
    </div>
</body>
</html>

app/views/exchanges/_perform_exchange.html.erb
<html>
<head>
    <%= stylesheet_link_tag    "results.css" %>
    <script type="text/javascript">
    $(document).ready(function() {
        $(".itemTemplate").each(function(){
            $(this).insertERBTemplateAjax();
        });
    });
    </script>
</head>
<body>
    <div class="container">
        <%= render 'shared/header' %>
        <div class="row">
            <div class="span6">
                <h3 id="myModalLabel">Perform Exchange</h3>
                <div class='align-center' id="exchangeStatus">
                    <div class="progress progress-striped">
                        <div class="bar" style="width: 50%;"></div>
                    </div>
                </div>
            </div>
        </div>

        <%= render 'exchange_header' %>        
        <%= render 'exchange_items' %> 
        <!-- Exchange Message-->
        <div class="row-fluid">
            <span>Message</span>
            <div class="rounded-map shadow" id="message" style="overflow:scroll; height: 100px;">
                <% current_message = @exch.message%>
                <% reply_message_id = current_message.id %>
                <% begin %>
                    <%= render :partial =>current_message, :locals => {:current_message => current_message} %>
                    <% reply_message_id = current_message.id %>
                    <% current_message = Message.where(:responseToMsgID => current_message.id).first %>
                <% end while(current_message != nil) %>
                <div>
                    <%= form_for Message.new, :remote => true, :html => {:class => "reply_message"} do |f| %>
         
                        <%= f.hidden_field :initUser, :value => current_user.id %>
                        <%= f.hidden_field :responseToMsgID, :value =>  reply_message_id %>
                        <% if is_current_user(@initUser) %>
                            <%= f.hidden_field :targUser, :value => @targUser.id %>
                        <% else %>
                            <%= f.hidden_field :targUser, :value => @initUser.id %>
                        <% end %>
                        <%= f.text_field :text %>
                        
                        <%= f.submit :reply, :class => "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div><!-- .row-fluid-->
    </div>

    <!--Opens Bottom Section-->
    <div class="row">
        <div class="span6 offset3">
            <% if((@exch.initUser).to_s == (current_user.id).to_s ) %>
                <% if @exch.initComp %>
                    Waiting for user
                <%else%>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <%= button_to "Accept", accept_perform_path(:exch_id => @exch.id, :user_id => @exch.initUser), :class => "btn btn-primary" %>
                <%end%>
            <%else%>
                <% if @exch.targComp %>
                    Waiting for user
                <%else%>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <%= button_to "Accept", accept_perform_path(:exch_id => @exch.id, :user_id => @exch.targUser), :class => "btn btn-primary" %>
                <%end%>
            <%end%>
        </div>
    </div>
</body>
</html>

app/views/exchanges/new_init.js.erb
var date = new Date();
var time = date.getTime();
$('#userItems .active').removeClass('active');
$('#userExchItems .active').removeClass('active');
$('#new_link').before("<li class='active'><a href='#listing"+time+"' data-toggle='tab'>NEW</li>");

$('#userExchItems').append("<div class='tab-pane active' id='listing"+time+"'><div id='addlisting' data-url='/add_need?init="+userContext.id+"&targ="+targContext.id+"'></div></div>");
$('#addlisting').insertERBTemplateAjax("over");