config/routes.rb
Kirpeep::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'auth/:provider/callback', :to => 'sessions#facebook_create'
  match 'auth/failure', to: redirect('/')
  match '/sessions/signin', :to => 'sessions#signin'

  match  'destroy_session',      :to => 'sessions#destroy'
  match  '/create_listing/',     :to => 'userlistings#create'
  match  '/new_listing',         :to => 'userlistings#new'
  match  '/exchange_listing/',   :to => 'userlistings#show_listing_exchange'
  match  '/show_listing/',       :to => 'userlistings#show_listing_result'
  match  '/destroy_listing',     :to => 'userlistings#destroy'
  match  '/share/:id',           :to => 'userlistings#share'
  match  '/profile/:id',         :to => 'users#profile'
  match  '/user_exchanges/:id',  :to => 'users#exchanges'
  match  '/messages/:id',        :to => 'users#messages'
  match  '/view/:id',            :to => 'users#view'
  match  '/users/:id/chat_status/:status', :to => 'users#chat_status'
  get  '/signup/',             :to => 'users#new'
  post   '/signup/',             :to => 'users#create'
  match  '/signup/:email&:pass', :to => 'users#new'
  match  '/users/:id/offers',    :to => 'users#offers'
  match  '/users/:id/needs/',    :to => 'users#needs'
  match  '/users/:id/need/:listing', :to => 'users#get_need'
  match  '/users/:id/offer/:listing', :to => 'users#get_offer'
  match '/users/:id/transactions', :to => 'transaction#show'
  match  '/search/',           :to => 'search#search'
  match  '/initiate_exchange/', :to => 'exchanges#initiate_exchange'
  match  '/create_exchange/', :to => 'exchanges#create'
  match  '/destroy_exchange/',  :to => 'exchanges#destroy'
  match  '/accept_exchange/', :to => 'exchanges#accept_exchange', :as => 'accept_exchange'
  match  '/accept_perform/' , :to => 'exchanges#accept_perform' , :as => 'accept_perform'
  match  '/rate_exchange/'  , :to => 'exchanges#rate_exchange' , :as => 'rate_exchange'
  match  '/add_offer/',   :to => 'exchanges#add_offer'
  match  '/add_need/',   :to => 'exchanges#add_need'
  match  '/exch_add_kirpoints/',    :to => 'exchanges#add_kirpoints_listing'
  match  '/sendmessage/', :to => 'messages#new'
  match  '/mark_unread/', :to => 'messages#markAsUnread'
  match  '/mark_read/', :to => 'messages#markAsRead'
  put '/userlisting/:id', :to => 'userlistings#update'
  get  '/edit_listing/',  :to => 'userlistings#edit'
  match  '/get_listing/', :to => 'userlistings#getListing'
  get '/userlisting/random', :to => 'userlistings#random'
  get '/userlisting/:id/ditto/', :to => 'userlistings#ditto'
  get '/userlisting/:id/edit_location/', :to => 'userlistings#edit_location'
  get  '/sendmessage/?id=:id&replyTo=:reply_message_id'    , :to => 'messages#new'
  match '/add_review/', :to => 'reviews#new'
  get '/forgot/', :to => 'users#forgot'
  post '/forgot', :to => 'users#process_forgot'
  get '/resetpassword/', :to => 'users#reset_password'
  post '/resetpassword/', :to => 'users#process_reset_password'
  get '/activate/', :to => 'users#activate'

  get '/kirpoints', :to => 'users#kirpoints'
  post '/kirpoints', :to => 'users#add_kirpoints'
  match '/kirpoints/confirm', :to=> 'users#confirm'
  match '/kirpoints/complete', :to=> 'users#complete'
  get '/kirpoints/cashout', :to=>'users#cashout_kirpoints'
  post '/kirpoints/cashout', :to=>'users#process_cashout_kirpoints'
  match 'kirpoints/gift', :to => 'users#gift_kirpoints'

  post '/sms/verify', :to => 'sms#verify'
  post '/sms/recieve', :to => 'sms#recieve'
  get '/listing/:id', :to => 'userlistings#show_listing'
  get '/listing/:id/report', :to => 'userlistings#report'

  match '/tos', :to => 'application#tos'
  match '/privacy', :to => 'application#privacy'
  match '/how', :to => 'application#how'
  match '/about', :to => 'application#about'
  match '/faq', :to => 'application#faq'
  post '/admin/credit', :to => 'admin#credit'
  
  post '/listingsmash/:id_y/over/:id_n/in/:time', :to => 'listing_smash#add_listing_smash_result'
  get  '/listingsmash/newlistings', :to => 'listing_smash#render_new_listings'
  get '/listingsmash/:lid1/vs/:lid2', :to => 'listing_smash#percentVs'
  get  '/listingsmash', :to => 'listing_smash#show'

  root :to => 'sessions#index'
  resources :search
  resources :users do |user|
  end
  resources :userlistings
  resources :sessions#, :only => [:new, :create, :destroy]
  resources :exchanges
  resources :profiles
  resources :messages
  resources :transaction
  resources :admin
  resources :sms, :only => [:verify, :recieve]
  resources :chat do |chat|
    post "reply", :to => "chat#reply"
  end

end

app/views/shared/_buy.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Purchase</h3>
</div>
<div class="modal-body">
	<div class="row-fluid">
	  	<span>You are buying</span>

	  	<!-- Be Sure to make partials for these listings-->
	  	<% @user_photo = listing.user.profile.photo.url %>
		<% if listing.type == 'Offer' %>
			<!-- Offer Listing -->
			<div class="rounded-offer">
				<div class="row-fluid">
					<span class="offer-span">OFFERED</span> 
					<span><%= listing.title %></span>
				</div>
				<div class="row-fluid">
					<p><%= listing.description %></p>
				</div>
				<div style= "display:none;">
				<%= image_tag('favorite.png') %> <!-- width="30" height="30" /><br /> -->
				<%= image_tag('kid.png') %> <!-- width="43" height="34" /> -->
				</div>
				<div class="row-fluid">
					<div class="span6">
					<%= link_to image_tag(@user_photo, {:width => '100px', :height => '100px'}), listing.user, {:id => 'userImage', 'rel' =>'popover' } %>
					<%= image_tag('stars.png') %>
					</div>
					<div id="offer-listing" class="span6">
						<div>
						<%= image_tag(listing.photo.url, {:width => '100px', :height => '100px'}) %> <!-- width="103" height="103" /> -->
						</div>
					</div>
				</div>
			</div>
		<%else%>
			<!-- Need Listing -->
			<div class="rounded-need">
				<div class="row-fluid">
					<span class="need-span">NEED</span> 
					<span><%= listing.title %></span>
				</div>
				<div class="row-fluid">
					<p><%= listing.description %></p>
				</div>
				<div style= "display:none;">
					<%= image_tag('favorite.png') %> <!-- width="30" height="30" /><br /> -->
					<%= image_tag('kid.png') %> <!-- width="43" height="34" /> -->
				</div>
				<div class="row-fluid">
					<div class="span6">
						<%= link_to image_tag(@user_photo, {:width => '100px', :height => '100px'}), listing.user, {:id => 'userImage', 'rel' =>'popover' } %>
						<%= image_tag('stars.png') %>
					</div>
			
					<div id="need-listing" class="span6">
						<div>
							<%= image_tag(listing.photo.url, {:width => '100px', :height => '100px'}) %>
						</div>
					</div>
				</div>
			</div>
		<%end%>
	<!-- End of listings-->
	</div>
</div>
<div class="modal-footer">
	<%= submit_tag 'Buy Now', :class => "btn" %>
</div>

app/views/shared/_dynamobox.html.erb
<div class="modal fade hide" id="listOffer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">List a Offer</h3>
  </div>
  <div class="modal-body">


  	<%= form_for([@user, Offer.new], :html => { :multipart => true }) do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

	      <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="field">
	    <%= f.label :photo %><br />
	    <%= f.file_field :photo %>
	  </div>
	  <div class="field">
	    <%= f.label :title %><br />
	    <%= f.text_field :title %>
	  </div>
	  <div class="field">
	    <%= f.label :description %><br />
	    <%= f.text_area :description  %><br />
	  </div>
	  <div class="field">
	    <%= f.label :inventoryCount %><br />
	    <%= f.text_field :inventoryCount %>
  	  </div>
	  <div class="photo_field">
	    <% f.fields_for :assets do |asset| %>
	      <%= asset.label :photo %><br />
	      <%= asset.file_field :photo %>
	    <%end%>
	  </div>
	  <div class="actions">
	    
	  </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
    <% end %> <!-- end of form -->
  </div>
</div>

app/views/shared/_footer.html.erb
<%# code for footer %>
<script id="_webengage_script_tag" type="text/javascript">
  window.webengageWidgetInit = window.webengageWidgetInit || function(){
    webengage.init({
      licenseCode:"~71680745"
    }).onReady(function(){
      webengage.render();
    });
  };

  (function(d){
    var _we = d.createElement('script');
    _we.type = 'text/javascript';
    _we.async = true;
    _we.src = (d.location.protocol == 'https:' ? "//ssl.widgets.webengage.com" : "//cdn.widgets.webengage.com") +
              "/js/widget/webengage-min-v-3.0.js";
    var _sNode = d.getElementById('_webengage_script_tag');
    _sNode.parentNode.insertBefore(_we, _sNode);
  })(document);
</script>

<div class='row' id="footer">	
	<div style='text-align:center; display:none'>
		Can’t find what you’re looking for? Try <span class="orange-mid">advanced search</span>, <span class="blue-mid">browse</span>, or <span class="green-mid">add your own listing</span>!
	</div>
	<div><hr /></div>
	<div class="row">
	  <div class='span4 pull-left' style='padding-left:5px !important;'>&copy; 2012-2013 Kirpeep, Inc.</div>
	  <div class='span4 pull-right' style='text-align:right;margin-right:5px;'><a href='/how'>How It Works</a> | <a href='/tos'>Terms of Use</a> | <a href='/privacy'>Privacy</a> | <a href='/about'>About Us</a> | <a href='/faq'>FAQ</a></div>
	</div>
</div>

<!-- Dynamobox Modal -->
<div class="modal fade hide" id="dynamobox" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>

app/views/shared/_header.html.erb
<div class='row' id='header'>
  <div class="span3" >
    <p>
      <%= link_to image_tag('kirpeep_head.png', :title=>"kirpeep_head"), root_url %> 
    </p>
  </div>
  <div class="span2" style='margin-top:20px;'>
    <%= form_tag search_path, :method => 'get', :class =>"form-search" do %>
      <div class="input-prepend input-append">
        <div class="btn-group">
	  <button class="btn dropdown-toggle" data-toggle="dropdown" style="width: 180px !important;">
        	<span id='catTitle'><%=if params[:category] && params[:category] != "" then params[:category] else "Categories" end%></span>
	       <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu" style='width:500px !important;'>
	    <% $categories.each do |cat| %>
		<li style='text-align:left;width:150px !important;float:left !important;'>
                  <a href='#' onclick='$("#catTitle").html("<%= cat %>");$("#category").val("<%= cat %>");' ><%= cat %></a>
                </li>
	    <% end %>
            <li><a href='#' onclick='$("#catTitle").html("Categories");$("#category").val("");' style='text-align:center;'><em>Clear Category</em></a></li>
	  </ul>
	</div>
        <%= hidden_field_tag :category, params[:category] %>
        <%= text_field_tag :search, params[:search] ,{ :class => 'span3' }%>
        <%= submit_tag "search", {:class => "btn"} %>
      </div>
    <% end %>
  </div>
  <div class="pull-right" style='margin-top:20px;'>
    <% if signed_in? %>
      
      <div class="btn-group pull-right">
        <a class="btn dropdown-toggle" data-toggle="dropdown" onclick='$(this).dropdown()' href="#" style='margin-left:5px;' >
            <%= current_user.name %> <!--= if current_user.kirpoints == nil then 0 else current_user.kirpoints end %> kps-->
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <!--li><%#= link_to 'Buy Kirpoints' , '/kirpoints', :class => "dynamolink" %></li-->
            <!--li><%#= link_to 'Gift Kirpoints' , '/kirpoints/gift', :class => "dynamolink" %></li-->
            <!--li><%#= link_to 'Cashout Kirpoints' , '/kirpoints/cashout' %></li-->
            <li><%= link_to 'Home', current_user %></li>
            <li><%= link_to 'Edit Profile' , edit_profile_path(current_user.profile), :class => "dynamolink" %></li>
            <li><%= link_to 'Edit Account', edit_user_path(current_user), :class => "dynamolink" %></li>
            <li><%= link_to 'Sign Out' , destroy_session_path %></li>
          
        </ul>
      </div>
      <span class='span3 pull-right'>
      <%= link_to raw('<i class="icon-plus-sign"></i> Need'), 
	   new_userlisting_path(:type => "need"), 
	   {:class => 'dynamolink btn btn-link pull-right', 'role' => "button", 'data-toggle' => "modal" }%>

      
      <%= link_to raw('<i class="icon-plus-sign"></i> Offer'), new_userlisting_path(:type => "offer"), 
           {:class => 'dynamolink btn btn-link pull-right', 'role' => "button", 'data-toggle' => "modal" }%>
      </span>
    <% else %>
      <div class='row pull-right'>
	      <a href='/forgot' class='dynamolink'>Forgot Password</a>
	      <a href="#signin" role="button" class="btn" data-toggle="modal" >Sign In</a>
      </div>
      <br><br>
    <%end%>
  </div>
</div> 

app/views/shared/_initiated_exchange.html.erb
<!--Modal-->
    <%# @targ_listing = UserListing.find(@exch.targ_list_id)%>
    <%# @init_listing = UserListing.find(@exch.init_list_id)%>

    <div class="modal-header">
        <button type="button" class="close" data-miss="modal" aria-hidden="true"></button>
        <h3> An exchange has been initiated with you! </h3>
    </div>

    <div class="modal-body">
        <!--user viewing -->
        <div class='row-fluid'>
            <div class='span4' id="userInfo">
                <br>
                <%= image_tag(current_user.profile.photo.url, {:width => '100px', :height => '100px'}) %><br>
                <%= current_user.name %>
            </div>
        
            <!--Kirpeep Exchage Status Logo -->
            <div class='span4 align-center' id="exchangeStatus">
                <p><%= image_tag('InitExchIco.png', {:width => '100px', :height => '100px'} ) %></p>
            </div>
            
            <!--exchange partner -->
            <div class='span4 align-right' id="exchangePartner" >
                <span id="with">exchanging with</span><br>
                <% if (current_user.id).to_s == (@initUser.id).to_s %>
                    <%= image_tag(@targUser.profile.photo.url, {:width => '100px', :height => '100px'}) %>
                    <br>
                    <%= @targUser.name %>
                <%else%>
                    <%= image_tag(@initUser.profile.photo.url, {:width => '100px', :height => '100px'}) %>
                    <br>
                    <%= @initUser.name %>
                <%end%>
            </div>
        </div> <!-- .row-fluid-->                
    
        <!--opens middle section-->
        <div class="row-fluid">
        <!-- Left Side-->
      		<div class="span6">
            	<div>
                    <span id="getting">You are getting...</span>
                </div>


            <!-- Start of tabs for items user is receiving--> 
            <% for item in @initItems %>
                <div class="itemTemplate" data-url=""><div>
            <%end%>
            <!-- End of tabs for items user is receiving--> 
            </div><!-- .span6-->


            <!--Right Side-->
            <div class="span6">
                <div>
                    <span id="getting">You are giving...</span>
                </div>

            <!-- Start of tabs for items targ is receiving--> 

            <!-- End of tabs for items targ is receiving--> 

            </div>
        <!-- Exchange Message-->
        <div class="row-fluid">
            <span>Message</span>
            <div class="rounded-map shadow" id="message" style="overflow:scroll; height: 100px;">
                <% exch_message_link = ExchangeMessageLink.where(:exchange_id => @exch.id).first %>
                <% current_message = Message.find(exch_message_link.message_id) %>
                <% reply_message_id = current_message.id %>
                <% begin %>
                    <%= render :partial =>current_message, :locals => {:current_message => current_message} %>
                    <% reply_message_id = current_message.id %>
                    <% current_message = Message.where(:responseToMsgID => current_message.id).first %>
                <% end while(current_message != nil) %>
                <div>
                    <%= form_for Message.new, :remote => true, :html => {:class => "reply_message"} do |f| %>
         
                        <%= f.hidden_field :initUser, :value => current_user.id %>
                        <%= f.hidden_field :responseToMsgID, :value =>  reply_message_id %>
                        <% if is_current_user(@initUser) %>
                            <%= f.hidden_field :targUser, :value => @targUser.id %>
                        <% else %>
                            <%= f.hidden_field :targUser, :value => @initUser.id %>
                        <% end %>
                        <%= f.text_field :text %>
                        
                        <%= f.submit :reply, :class => "btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div><!-- .row-fluid-->
    </div>
    
    <!--Opens Bottom Section-->
    <div class="modal-footer">
        <div id="submitButton">
            <% if((@exch.initUser).to_s == (current_user.id).to_s ) %>
                <% if @exch.initAcpt %>
                    <span>Waiting for user</span>
                <%else%>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <%= f.submit "Sign In", {:class => "btn btn-primary"} %>
                <!--<%= button_to "Accept", accept_exchange_path(:exch_id => @exch.id, :user_id => @exch.initUser) %>-->
                <%end%>
            <%else%>
                <% if @exch.targAcpt %>
                    <span>Waiting for user</span>
                <%else%>
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <%= button_to "Accept", accept_exchange_path(:exch_id => @exch.id, :user_id => @exch.targUser), {:class => "btn btn-primary"} %>
                <%end%>
            <%end%>    
        </div>
    </div>

app/views/shared/_list_need.erb
<script type="text/javascript">
       $('#new_need').submit(function(){
           var valuesToSubmit = $(this).serialize();
           console.log('pre ajax post');
           $.ajax({
               url: '/list_need/'+userID, //$(this).attr('action'), //sumbits it to the given url of the form
               data: valuesToSubmit,
               dataType: "JSON", // you want a difference between normal and ajax-calls, and json is standard
               type: "POST"
           }).success(function(json){
                $.ajax({
                  url: '/user_needs.json',
		  dataType: 'JSON'
		}).success(function(data){
			console.log(data);
			LoadNeeds(data);
			var count = parseInt($('#needCount').html());
			count++;
			$('#needCount').html(count);
		});
                $('#dynamobox').modal('toggle');
           });
           return false; // prevents the normal post
       });
</script>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">List A Need</h3>
</div>
<%= form_for([@user, Need.new], :html => { :multipart => true }) do |f| %>
<div class="modal-body">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description  %><br />
  </div>
    <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
	<%= f.label :quantityUnit %><br />
	<%= f.text_field :quantityUnit %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
</div>
<div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	<%= f.submit 'Save', :class => "btn" %>
	<% end %>
</div>

app/views/shared/_need_form.html.erb
<%= form_for([@user, Need.new], :html => { :multipart => true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description  %><br />
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :quantityUnit %><br />
    <%= f.text_field :quantityUnit %>
  </div>
  <div class="photo_field">
    <% f.fields_for :assets do |asset| %>
      <%= asset.label :photo %><br />
      <%= asset.file_field :photo %>
    <%end%>
  </div>
  <div class="actions">
    <%= f.submit 'Save'%>
  </div>
<% end %>

app/views/shared/_need_listing.html.erb
<div class="rounded-need shadow">
    <% if @targ_listing.type == "Need" %>
    <div style="">
        <%= image_tag(@targ_listing.photo.url, {:width => "50px", :height => '50px'} )%>
	<img src='' style='width:50px;height50px;' />
    </div>
    <div style="">
        <span>NEEDED</span> 
    </div>
    <div style="">
        <%= @targ_listing.title %>
        <%= @targ_listing.quantity %> <%= @targ_listing.quantityUnit %>
        Description: <%= @targ_listing.description %>
        
        <%= f.hidden_field :targ_list_id, :value => @targ_listing.id %>
        <%= f.hidden_field :targUser, :value => @targ_listing.user.id %>
    </div>
    <%else%>
    <span id="selectOffer">Select an offer or (link to create)create a new one.</span>
    <div>
        <% offers_array = @user.offers.all.map { |offer| [offer.title, offer.id] } %> 
        <%= f.select :init_list_id, options_for_select(offers_array) %>
        <%= f.hidden_field(:initUser, :value => current_user.id ) %>
    </div>
    <%end%>
</div>

app/views/shared/_offer_form.html.erb
<%= form_for([@user, Offer.new], :html => { :multipart => true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description  %><br />
  </div>
  <div class="field">
    <%= f.label :inventoryCount %><br />
    <%= f.text_field :inventoryCount %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <!-- add listing type -->
  <div class="actions">
    <%= f.submit 'Save'%>
  </div>
<% end %>

app/views/shared/_offer_listing.html.erb
<!-- Offer Listing -->
<div class="rounded-offer shadow">
    <% if @targ_listing.type == "Offer" %>
    <div style="">
        <%= image_tag(@targ_listing.photo.url, {:width => "50px", :height => '50px'}) %>
    </div>
    <div style="">
        <span>OFFERED</span> 
    </div>
    <div style="">
        <span>
        <%= @targ_listing.title %>
        <%= @targ_listing.inventoryCount %>
        <%= @targ_listing.description %>
        <%= f.hidden_field(:targ_list_id, :value => @targ_listing.id ) %>
        <%= f.hidden_field :targUser, :value => @targ_listing.user.id  %>
        <!-- %= link_to '<span id="selectNeed">Select a need or <%= link_to "create", new_offer_path, :class => "CreateOffer" %> a new one.</span>
    <div>
        <% needs_array = @user.needs.all.map { |need| [need.title, need.id] } %> 
        <%= f.select :init_list_id, options_for_select(needs_array) %>
        <%= f.hidden_field :initUser, :value => current_user.id  %>
    </div>EDIT', edit_offer_path(:id => offer.id) %-->
        </span>
    </div> 
    <%else%>
    <span id="selectNeed">Select a need or <%= link_to "create", new_userlisting_path(:type => "offer"), :class => "CreateOffer" %> a new one.</span>
    <div>
        <% needs_array = @user.needs.all.map { |need| [need.title, need.id] } %> 
        <%= f.select :init_list_id, options_for_select(needs_array) %>
        <%= f.hidden_field :initUser, :value => current_user.id  %>
    </div>
    <%end%>
</div><!-- End of Offer Listing -->

app/views/shared/_signin.html.erb
<div class="modal fade hide" id="signin" tabindex="-1" role="dialog" aria-labelledby="signinLabel" aria-hidden="true">
  <div class="modal-header">
    <a type="button" class="close" data-dismiss="modal" aria-hidden="true">×</a>
    <h3 id="signinLabel">Sign In</h3>
  </div>
  <div class="modal-body">
    <%= flash[:error] %>

    <%= form_for(:session, :url => sessions_path) do |f| %>
      <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :password%>
        <%= f.password_field :password %>
      </div>
    
      <div class="modal-footer">
        <a class="btn" data-dismiss="modal" aria-hidden="true">Close</a>
        <%= f.submit "Sign In", {:class => "btn btn-primary"} %>
      </div>
    <%end%>
  </div>
</div>